language: php

php:
  - 7.4

env:
  - TEST_SUITE=tests

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.4

install:
  - composer install

script:
  - vendor/bin/phpunit --debug --verbose --configuration phpunit.xml --testsuite "$TEST_SUITE"
